on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl 'https://marknad.vatterhem.se/API/Service/SearchServiceHandler.ashx' \
          -H 'Connection: keep-alive' \
          -H 'Pragma: no-cache' \
          -H 'Cache-Control: no-cache' \
          -H 'Accept: application/json,text/*' \
          -H 'X-Requested-With: XMLHttpRequest' \
          -H 'X-Momentum-API-KEY: VAhlmZODykjynHEn2lV4/HO8tPFzKbPcIKcNNfPj/5M=' \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -H 'Origin: https://marknad.vatterhem.se' \
          -H 'Sec-Fetch-Site: same-origin' \
          -H 'Sec-Fetch-Mode: cors' \
          -H 'Sec-Fetch-Dest: empty' \
          -H 'Referer: https://marknad.vatterhem.se/?mg=1' \
          -H 'Accept-Language: en-US,en;q=0.9,sv-SE;q=0.8,sv;q=0.7' --data-raw 'Parm1=%7B%22CompanyNo%22%3A-1%2C%22SyndicateNo%22%3A1%2C%22ObjectMainGroupNo%22%3A1%2C%22Advertisements%22%3A%5B%7B%22No%22%3A-1%7D%5D%2C%22RentLimit%22%3A%7B%22Min%22%3A0%2C%22Max%22%3A20000%7D%2C%22AreaLimit%22%3A%7B%22Min%22%3A0%2C%22Max%22%3A200%7D%2C%22ApplySearchFilter%22%3Atrue%2C%22Page%22%3A1%2C%22Take%22%3A1000000%2C%22SortOrder%22%3A%22ObjectNo+ASC%2C+StreetName+ASC%22%2C%22ReturnParameters%22%3A%5B%22ObjectNo%22%2C%22FirstEstateImageUrl%22%2C%22Street%22%2C%22SeekAreaDescription%22%2C%22PlaceName%22%2C%22ObjectSubDescription%22%2C%22ObjectArea%22%2C%22RentPerMonth%22%2C%22MarketPlaceDescription%22%2C%22CountInterest%22%2C%22FirstInfoTextShort%22%2C%22FirstInfoText%22%2C%22EndPeriodMP%22%2C%22FreeFrom%22%2C%22SeekAreaUrl%22%2C%22Latitude%22%2C%22Longitude%22%2C%22BoardNo%22%5D%7D&CallbackMethod=PostObjectSearch&CallbackParmCount=1&__WWEVENTCALLBACK=&' --compressed  | \
          jq "del(.Result[].RowId)" > vatterhem.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
